name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install i686 target
      run: rustup target add i686-unknown-linux-gnu
    - name: Install aarch64 target
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-targets
    - name: Run tests in release mode
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-targets --release
    - name: Run tests (i686)
      uses: actions-rs/cargo@v1
      with:
        command: test
        use-cross: true
        args: --all-targets --target i686-unknown-linux-gnu
    - name: Run tests in release mode (i686)
      uses: actions-rs/cargo@v1
      with:
        command: test
        use-cross: true
        args: --all-targets --target i686-unknown-linux-gnu --release
    - name: Run tests (aarch64)
      uses: actions-rs/cargo@v1
      with:
        command: test
        use-cross: true
        args: --all-targets --target aarch64-unknown-linux-gnu
    - name: Run tests in release mode (aarch64)
      uses: actions-rs/cargo@v1
      with:
        command: test
        use-cross: true
        args: --all-targets --target aarch64-unknown-linux-gnu --release
    - name: Build fuzzer
      run: cd fuzz; cargo test
